package com.dbcopilot.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.ArrayList;
import java.util.List;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "PostgreSQL EXPLAIN query plan analysis and optimization suggestions")
public class QueryPlanAnalysis {

    @Schema(description = "Raw JSON / Text plan returned from EXPLAIN (ANALYZE, BUFFERS)")
    private String rawPlan;

    @Schema(description = "Estimated total query startup & execution cost", example = "42.15")
    private Double totalCost;

    @Schema(description = "Actual execution time reported by database in milliseconds", example = "1.85")
    private Double actualExecutionTimeMs;

    @Schema(description = "Whether a high-cost Sequential Scan was detected on large tables", example = "false")
    private boolean sequentialScanDetected;

    @Schema(description = "Names of tables scanned sequentially without an index")
    private List<String> scannedTables;

    @Builder.Default
    @Schema(description = "Actionable optimization recommendations generated by the AI optimizer agent")
    private List<String> recommendations = new ArrayList<>();

    @Builder.Default
    @Schema(description = "Recommended DDL statements (such as CREATE INDEX) to boost performance")
    private List<String> suggestedIndexes = new ArrayList<>();
}
