package com.dbcopilot.service;

import com.dbcopilot.dto.DatabaseQueryResult;
import com.dbcopilot.dto.QueryPlanAnalysis;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import javax.sql.DataSource;
import java.sql.*;
import java.util.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

@Slf4j
@Service
@RequiredArgsConstructor
public class DatabaseExecutionService {

    private final DataSource dataSource;

    @Value("${copilot.guardrails.read-only-enforced:true}")
    private boolean enforceReadOnly;

    @Value("${copilot.guardrails.max-execution-time-ms:5000}")
    private int maxExecutionTimeMs;

    @Value("${copilot.guardrails.max-rows-returned:100}")
    private int maxRowsReturned;

    private static final List<String> FORBIDDEN_KEYWORDS = List.of(
            "DROP", "TRUNCATE", "ALTER", "GRANT", "REVOKE", "CREATE USER", "DROP USER",
            "VACUUM", "REINDEX", "EXEC", "EXECUTE", "SHUTDOWN"
    );

    private static final Pattern DML_PATTERN = Pattern.compile("^\\s*(INSERT|UPDATE|DELETE)\\b", Pattern.CASE_INSENSITIVE);

    /**
     * Cleans and sanitizes raw SQL generated by LLMs (strips markdown formatting, comments, extra semicolons)
     */
    public String sanitizeSql(String rawSql) {
        if (rawSql == null) return "";
        String sql = rawSql.trim();

        // Extract SQL from markdown code fences if present
        if (sql.contains("```sql")) {
            int start = sql.indexOf("```sql") + 6;
            int end = sql.indexOf("```", start);
            if (end != -1) {
                sql = sql.substring(start, end);
            } else {
                sql = sql.substring(start);
            }
        } else if (sql.contains("```")) {
            int start = sql.indexOf("```") + 3;
            int end = sql.indexOf("```", start);
            if (end != -1) {
                sql = sql.substring(start, end);
            } else {
                sql = sql.substring(start);
            }
        }

        sql = sql.trim();
        // Remove trailing semicolon if present
        if (sql.endsWith(";")) {
            sql = sql.substring(0, sql.length() - 1).trim();
        }
        return sql;
    }

    /**
     * Validates that the SQL query conforms to security guardrails
     */
    public void validateGuardrails(String sql) throws SecurityException {
        String upper = sql.toUpperCase();

        for (String forbidden : FORBIDDEN_KEYWORDS) {
            Pattern p = Pattern.compile("\\b" + forbidden + "\\b", Pattern.CASE_INSENSITIVE);
            if (p.matcher(upper).find()) {
                throw new SecurityException("Query rejected by security guardrails: Forbidden keyword '" + forbidden + "' detected.");
            }
        }

        if (enforceReadOnly && DML_PATTERN.matcher(sql).find()) {
            throw new SecurityException("Query rejected: Database is configured in READ-ONLY mode. INSERT/UPDATE/DELETE statements are not permitted.");
        }
    }

    /**
     * Executes SQL query on the relational database and returns formatted tabular results
     */
    public DatabaseQueryResult executeQuery(String rawSql) {
        String sql = sanitizeSql(rawSql);
        long startTime = System.currentTimeMillis();

        try {
            validateGuardrails(sql);
        } catch (SecurityException se) {
            return DatabaseQueryResult.builder()
                    .success(false)
                    .errorMessage(se.getMessage())
                    .executionTimeMs(System.currentTimeMillis() - startTime)
                    .build();
        }

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            conn.setReadOnly(enforceReadOnly);
            stmt.setQueryTimeout(Math.max(1, maxExecutionTimeMs / 1000));
            stmt.setMaxRows(maxRowsReturned);

            boolean hasResultSet = stmt.execute(sql);

            if (hasResultSet) {
                try (ResultSet rs = stmt.getResultSet()) {
                    ResultSetMetaData rsmd = rs.getMetaData();
                    int colCount = rsmd.getColumnCount();

                    List<String> columns = new ArrayList<>(colCount);
                    List<String> columnTypes = new ArrayList<>(colCount);
                    for (int i = 1; i <= colCount; i++) {
                        columns.add(rsmd.getColumnLabel(i));
                        columnTypes.add(rsmd.getColumnTypeName(i));
                    }

                    List<Map<String, Object>> rows = new ArrayList<>();
                    while (rs.next()) {
                        Map<String, Object> row = new LinkedHashMap<>(colCount);
                        for (int i = 1; i <= colCount; i++) {
                            row.put(columns.get(i - 1), rs.getObject(i));
                        }
                        rows.add(row);
                    }

                    long elapsed = System.currentTimeMillis() - startTime;
                    return DatabaseQueryResult.builder()
                            .success(true)
                            .columns(columns)
                            .columnTypes(columnTypes)
                            .rows(rows)
                            .rowCount(rows.size())
                            .executionTimeMs(elapsed)
                            .build();
                }
            } else {
                int updateCount = stmt.getUpdateCount();
                long elapsed = System.currentTimeMillis() - startTime;
                return DatabaseQueryResult.builder()
                        .success(true)
                        .rowCount(updateCount)
                        .executionTimeMs(elapsed)
                        .build();
            }

        } catch (SQLException e) {
            long elapsed = System.currentTimeMillis() - startTime;
            log.warn("SQL Execution failed for query: [{}] - Error: {}", sql, e.getMessage());
            return DatabaseQueryResult.builder()
                    .success(false)
                    .errorMessage(e.getMessage())
                    .sqlState(e.getSQLState())
                    .executionTimeMs(elapsed)
                    .build();
        }
    }

    /**
     * Executes EXPLAIN query plan analysis to inspect performance bottlenecks
     */
    public QueryPlanAnalysis explainQueryPlan(String rawSql) {
        String sql = sanitizeSql(rawSql);
        String explainSql = "EXPLAIN (ANALYZE, COSTS, BUFFERS) " + sql;

        try (Connection conn = dataSource.getConnection();
             Statement stmt = conn.createStatement()) {

            // If not postgres (e.g. H2 in test), run simple EXPLAIN
            DatabaseMetaData metaData = conn.getMetaData();
            if ("H2".equalsIgnoreCase(metaData.getDatabaseProductName())) {
                explainSql = "EXPLAIN " + sql;
            }

            try (ResultSet rs = stmt.executeQuery(explainSql)) {
                StringBuilder planBuilder = new StringBuilder();
                boolean seqScanDetected = false;
                List<String> scannedTables = new ArrayList<>();
                Double totalCost = null;
                Double actualTime = null;

                Pattern costPattern = Pattern.compile("cost=\\d+\\.\\d+\\.\\.(\\d+\\.\\d+)");
                Pattern timePattern = Pattern.compile("actual time=\\d+\\.\\d+\\.\\.(\\d+\\.\\d+)");
                Pattern seqScanPattern = Pattern.compile("Seq Scan on (\\w+)");

                while (rs.next()) {
                    String line = rs.getString(1);
                    planBuilder.append(line).append("\n");

                    if (totalCost == null) {
                        Matcher cm = costPattern.matcher(line);
                        if (cm.find()) {
                            try {
                                totalCost = Double.parseDouble(cm.group(1));
                            } catch (Exception ignored) {}
                        }
                    }

                    if (actualTime == null) {
                        Matcher tm = timePattern.matcher(line);
                        if (tm.find()) {
                            try {
                                actualTime = Double.parseDouble(tm.group(1));
                            } catch (Exception ignored) {}
                        }
                    }

                    Matcher sm = seqScanPattern.matcher(line);
                    if (sm.find()) {
                        seqScanDetected = true;
                        String table = sm.group(1);
                        if (!scannedTables.contains(table)) {
                            scannedTables.add(table);
                        }
                    }
                }

                List<String> recommendations = new ArrayList<>();
                List<String> suggestedIndexes = new ArrayList<>();

                if (seqScanDetected) {
                    recommendations.add("Sequential table scan detected on table(s): " + String.join(", ", scannedTables) + ". Consider adding composite B-Tree indexes on filtered/joined columns.");
                    for (String t : scannedTables) {
                        suggestedIndexes.add(String.format("CREATE INDEX IF NOT EXISTS idx_%s_optimizer ON %s (...);", t, t));
                    }
                } else {
                    recommendations.add("Query utilizes available index paths with low scan overhead.");
                }

                return QueryPlanAnalysis.builder()
                        .rawPlan(planBuilder.toString().trim())
                        .totalCost(totalCost != null ? totalCost : 10.0)
                        .actualExecutionTimeMs(actualTime != null ? actualTime : 1.5)
                        .sequentialScanDetected(seqScanDetected)
                        .scannedTables(scannedTables)
                        .recommendations(recommendations)
                        .suggestedIndexes(suggestedIndexes)
                        .build();
            }
        } catch (SQLException e) {
            log.warn("EXPLAIN plan execution failed: {}", e.getMessage());
            return QueryPlanAnalysis.builder()
                    .rawPlan("EXPLAIN plan not available: " + e.getMessage())
                    .totalCost(0.0)
                    .actualExecutionTimeMs(0.0)
                    .sequentialScanDetected(false)
                    .recommendations(List.of("Ensure database supports EXPLAIN ANALYZE syntax."))
                    .build();
        }
    }
}
